# Generated by Django 3.1.1 on 2020-09-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('colour', models.CharField(choices=[('#F1C40F', 'Dark Orange'), ('#CD5C5C', 'Indian Red'), ('#F08080', 'Light Coral'), ('#000000', 'Black'), ('#FFFF00', 'Yellow'), ('#FF00FF', 'Fuschia'), ('#C0C0C0', 'Silver')], default='#C0C0C0', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
